name: Update gist with WakaTime stats

on:
  push:
    branches: 
      - master
  schedule:
    - cron: "0 * * * *"
    

jobs:

  build:
    name: Upddate-gist
    runs-on: ubuntu-latest
    env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: e825105400c0b5cfb6fb15b19c7c62ed
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}

    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Update-gist
      run:  go run ./cmd/main.go


   
 
